export const FORMAT = {
  CONVENTIONAL: 'CONVENTIONAL',
  THOUGHTWORKS: 'THOUGHTWORKS'
}

export const INTEGRATION = {
  TRELLO: 'TRELLO',
  JIRA: 'JIRA'
}

export const INPUT_MANUALLY = 'INPUT_MANUALLY'
